export const QUESTIONS_LOADED = 'QUESTIONS_LOADED';
export const QUESTIONS_REQUESTED = 'QUESTIONS_REQUESTED';
export const QUESTIONS_ERROR = 'QUESTIONS_ERROR';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const SET_TOTAL_ITEMS_COUNT = 'SET_TOTAL_ITEMS_COUNT';
export const QUESTIONS_FILTER = '!B96NeMwIYiJQy*bdTim)okETGvVkZz';